services:

  database:
    container_name: SmartSocial_db
    image: postgres:15-alpine
    volumes:
      - SmartSocial_postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  SmartSocial_postgres:
